services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  client:
    build:
      context: ./client
    ports:
      - "8080:8080"
    depends_on:
      - server
